#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
# if [ -x "$(command -v picom)" ]; then
  # picom --experimental-backends &> /dev/null &
  # picom &> /dev/null &
# elif [ -x "$(command -v compton)" ]; then
  # compton &> /dev/null &
# fi

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$command -v wallc" ]; then
    BACKGROUND = $SCRIPTPATH/$(ls $SCRIPTPATH/background* | shuf -n 1)
    wallc set $BACKGROUND
fi

# Conky
# ~/.config/conky/start-conky.sh &

# start eww daemon
eww daemon &

#open eww windows
eww open-many left tags right

#write uhrwerk to temporary file
# uhrwerk > /tmp/uhrwerk &
