#!/usr/bin/env bash

update_sink() {
    sink=$(pacmd list-sinks | sed -n '/\* index:/ s/.*: //p')
}

volume_up() {
    update_sink
    pactl set-sink-volume "$sink" +1%
}

volume_down() {
    update_sink
    pactl set-sink-volume "$sink" -1%
}

volume_mute() {
    update_sink
    pactl set-sink-mute "$sink" toggle
}

volume_print() {
    update_sink

    active_port=$(pacmd list-sinks | sed -n "/index: $sink/,/index:/p" | grep active)
    muted=$(pulseaudio-ctl full-status | awk '{print $2}')

    if echo "$active_port" | grep -q speaker && echo "$muted" | grep -q yes; then
        icon="遼"
    elif echo "$active_port" | grep -q headphones && echo "$muted" | grep -q no; then
        icon=""
    elif echo "$active_port" | grep -q headphones && echo "$muted" | grep -q yes; then
        icon="ﳌ"
    else
        icon="蓼"
    fi
    
    echo "$icon"
}

listen() {
    volume_print

    pactl subscribe | while read -r event; do
        if echo "$event" | grep -qv "Client"; then
            volume_print
        fi
    done
}

case "$1" in
    --up)
        volume_up
        ;;
    --down)
        volume_down
        ;;
    --mute)
        volume_mute
        ;;
    *)
        listen
        ;;
esac
